### ISSUE TITLE
A glitch with sk!give.

### ISSUE THREAD

**Issue by BlobFreeman** [exsersewo/Skuld#1]
sk!give seems to have a problem where it resets the users money amount to 1 when that person is gifted money
![schermafbeelding 2017-05-30 om 17 02 04](https://cloud.githubusercontent.com/assets/29065966/26590003/cbd8be38-4559-11e7-976b-7037c7215d2e.png)

**Comment by exsersewo** [comment]
Fixed and released with 0.3.0.7
