### ISSUE TITLE
A problem with the sk!pasta upvote

### ISSUE THREAD

**Issue by BlobFreeman** [exsersewo/Skuld#2]
sk!pasta upvote has a "bug" where you can upvote a non existent pastas
![schermafbeelding 2017-05-30 om 17 03 40](https://cloud.githubusercontent.com/assets/29065966/26590220/45b27f28-455a-11e7-81f6-701c5ab61f5d.png)
![schermafbeelding 2017-05-30 om 17 06 23](https://cloud.githubusercontent.com/assets/29065966/26590247/53f38424-455a-11e7-90a0-221d2aad915b.png)

**Comment by exsersewo** [comment]
Fixed and will be added in 0.3.0.7
